# Generated by Django 4.2.7 on 2025-05-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commande_article_seuil_alerte_mouvementstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlenumeroserie',
            name='mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mouvementstock'),
        ),
    ]
