# Generated by Django 4.2.7 on 2025-05-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_articlenumeroserie_mouvement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='quantite_stock',
        ),
    ]
