# Generated by Django 5.1.7 on 2025-05-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_commande_utilisateur_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
    ]
